server:
  port: 9090
  
spring:
 application:
    name: spring-data-rest
    
    
 datasource:
  plateform: h2
    url:jdbc:h2:mem:mail   
     
h2:
 console:
   enabled: true
   
   jpa:
     hibernate:
      ddl-auto: update